# POST  http://localhost:3003/api/blogs/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzIzNmU4ZGRhMjQ3NWNiZDlmY2VmN2EiLCJpYXQiOjE3MzAzNzY0NTh9._qYf-KKuwKNvbAOoIPqq7cREaj4UggqUcuVKDxJVK1s

# {
#     "title": "Love Expresso Coffee",
#     "author": "Expresso maker",
#     "url": "http://www.expresso.html",
#     "likes": 100
# }

# DELETE http://localhost:3003/api/blogs/67161b94f9c0cbae54963390
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzE0MDI0NjE0MTE0ZTQwYzkwZGFiODEiLCJpYXQois5yXrHzTfTGZmfgoYeNkANagyCPT9hrnyyJECODxY


# GET http://localhost:3003/api/users/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzE0MDI0NjE0MTE0ZTQwYzkwZGFiODEiLCJpYXQiOjE3Mjk0MzE3MTd9.ois5yXrHzTfTGZmfgoYeNkANagyCPT9hrnyyJECODxY

# DELETE http://localhost:3003/api/blogs/6713fd47725dc63a6aa7f32e
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzE0MDI0NjE0MTE0ZTQwYzkwZGFiODEiLCJpYXQiOjE3Mjk0MzE3MTd9.ois5yXrHzTfTGZmfgoYeNkANagyCPT9hrnyyJECODxY



# GET http://localhost:3003/api/blogs/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NzI4ODM1MzJmOWVjMzMyODdkYjhiN2YiLCJpYXQiOjE3MzA3MDg5MTd9.GaoqpSieujvLgMUlgg4ean5ov9Jbps7t0ETVZOtBS_E


# GET http://localhost:3003/api/users/


# POST http://localhost:3003/api/users/
# Content-Type: application/json

# {
#     "username": "mluukkainen",
#     "name": "Matti Luukkainen",
#     "password" : "mluukkainen"
# }



# POST http://localhost:3003/api/login/
# Content-Type: application/json

# {
#     "username": "testuser",
#     "password": "testpasswordHash"
# }




#   "id": "671856656a6e42482854fa77"
# }


# PUT http://localhost:3003/api/blogs/6718d0f2a6678b0477927bfa
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpbmVuIiwiaWQiOiI2NzE4NDQ0NjZhNmU0MjQ4Mjg1NGZhNDciLCJpYXQiOjE3Mjk4MTExMzZ9.8ZQT6pmA-E-KCf-ZA1TCS22taFLIQJxl7bKf7Bxyp3I

# {
#     "title": "October Grimes",
#     "likes": 20
# }